// For token
export const SET_VALID_TOKEN = 'SET_TOKEN';
export const SET_INVALID_TOKEN = 'SET_INVALID_TOKEN';

// For characters
export const SET_CHARACTERS = 'SET_CHARACTERS';
export const ADD_CHARACTER_TO_FAV_LIST = 'ADD_CHARACTER_TO_FAV_LIST';
export const REMOVE_CHARACTER_FROM_FAV_LIST = 'REMOVE_CHARACTER_FROM_FAV_LIST';
